### ISSUE TITLE
Newsletter section is kind of forgotten at the bottom. 

### ISSUE THREAD

**Issue by MandyMeindersma** [devedmonton/DES-Website#188]
this section:
![image](https://github.com/devedmonton/DES-Website/assets/17459171/22cf2339-7911-4ecc-91fc-e3839ceb354a)

I am not sure what to do with it. I want to put a link to it in the menu but our menu is already too full. 

Maybe I just want to put it higher on the page? Like just below the slack stuff? idk. 

This ticket might involve some discussion between us on what to do.

**Comment by olimpiuus** [comment]
The problem is that if we move it upper, people who already signed will see useless information.
Let's keep it at the bottom but make it a pop-up. Let's show it after 1 min of browsing the webpage. 
But it could be annoying if you are already signed up for it. 
I bet we could track who was signed up for newsletters by cookies. So we can add the "already sighed" button in a pop-up to not annoy people who were already sighed. The problem with cookies is that they could be deleted, or you can visit a website from another device. But without adding authentification, it is the best solution for my view.

**Comment by olimpiuus** [comment]
> this section: ![image](https://user-images.githubusercontent.com/17459171/258654023-22cf2339-7911-4ecc-91fc-e3839ceb354a.png)
> 
> I am not sure what to do with it. I want to put a link to it in the menu but our menu is already too full.
> 
> Maybe I just want to put it higher on the page? Like just below the slack stuff? idk.
> 
> This ticket might involve some discussion between us on what to do.

The problem is that if we move it upper, people who already signed will see useless information.
Let's keep it at the bottom but make it a pop-up. Let's show it after 1 min of browsing the webpage.
But it could be annoying if you are already signed up for it.

I bet we could track who was signed up for newsletters by cookies. So we can add the "already sighed" button in a pop-up to not annoy people who were already sighed. The problem with cookies is that they could be deleted, or you can visit a website from another device. But without adding authentification, it is the best solution for my view.

**Comment by MandyMeindersma** [comment]
A possible issue with cookies is that we already have 150 people on our newsletter that wouldn't have that cookie. That would find the newsletter pop up useless too. 

What about an email logo on the socials part of the menu? that might be confusing though

**Comment by MandyMeindersma** [comment]
https://www.flaticon.com/free-icon/newsletter_1042744

Maybe something like this but idk how small the writing would be

**Comment by olimpiuus** [comment]
To add extra button with link to newsletter section will be easy and not much in code. 
But if you are not against to add pop up, because it should lead to more subscribers. And old ones would turn it off. 

I can firstly add button,and then make pop up .

**Comment by deejayjay** [comment]
I kind of think that the pop-up is annoying. I like adding another icon in the social media icons list better. Or we could add a floating icon that stays on the bottom right corner of the screen and have a modal pop up when the icon is clicked.

**Comment by MandyMeindersma** [comment]
Once this pr #274  is in then we can just add it to the bigger menu :)
