### ISSUE TITLE
`npm run pr-checks` should pass on main and when I run prettier it shouldn't make changes to these files

### ISSUE THREAD

**Issue by MandyMeindersma** [devedmonton/DES-Website#259]
![image](https://github.com/devedmonton/DES-Website/assets/17459171/f74ed14c-0b7c-4156-8571-405f4460d53e)

We can probably just ignore:
.all-contributorsrc
README.md
store/joinslacklink.js

**Comment by DerrykBoyd** [comment]
I have update the ignore file in #263 to include the all-contrubutors and markdown files. 

The joinslacklink.js was a valid formatting error that was committed, we might want to open an issue to add some automated checks to the PR process to enforce the `pr-checks` script rather than relying on self reporting.

**Comment by MandyMeindersma** [comment]
good idea #265
