### ISSUE TITLE
Add word press to our list of meetups!

### ISSUE THREAD

**Issue by MandyMeindersma** [devedmonton/DES-Website#370]
Add word press to this list of meetups: https://devedmonton.com/meetups

**Comment by shrutiijain26** [comment]
Please assign this issue to me. I've already made a pull request addressing it, and I would appreciate it if you could review it.

**Comment by MandyMeindersma** [comment]
I am sorry I shouldn't have put pr welcome on this pr, I am still waiting for some info from the organizer, my mistake

**Comment by shrutiijain26** [comment]
Here’s a rephrased version of your reply:

"I encountered an authentication error, which is why I asked @blizet to handle it. If necessary, I can redo the process once the requirements are clarified. Could you please assign the issue to me? Moving forward, @blizet and I will ensure that everything is handled from our respective accounts, and there will be no more forwarded merges."

**Comment by MandyMeindersma** [comment]
The issue is already assigned to you.

I don't know when this will be ready to work on though. I can add updates here.

**Comment by MandyMeindersma** [comment]
This is the link for them: https://www.linkedin.com/groups/14490539

**Comment by MandyMeindersma** [comment]
Okay this one is ready to work on now! https://ik.imagekit.io/des/meetups/wordpress.png?updatedAt=1728262345205

So sorry @shrutiijain26 ! 

Did you still want to work on it?

**Comment by shrutiijain26** [comment]
Sure
