### ISSUE TITLE
BUG: Multiday events on the calendar not showing up on the events page.

### ISSUE THREAD

**Issue by dgmouris** [devedmonton/DES-Website#418]
I tried to add a multiday event to the calendar so that folks can see the devedmonton hackathon but it's not quite showing up as expected.

The google calendar and the https://devedmonton.com/api/events shown here.
![image](https://github.com/user-attachments/assets/b9c735ed-7d3b-44d2-b490-48e74ee9ba36)

The event doesn't seem to show up 
![image](https://github.com/user-attachments/assets/a1e879c7-ab69-496d-ac70-62711662ef87)

I know @keifererikson might know a little bit about this.

As a temporary measure I'll just make three separate events here :)

Note references: https://github.com/devedmonton/DES-Website/issues/312

**Comment by keifererikson** [comment]
@charrde with the quick fix! Thanks for that! 

@dgmouris another win for Open Source Club! 😻 Let's go!

**Comment by dgmouris** [comment]
@charrde thanks a bunch this looks great!

@keifererikson yay open source club wins!

**Comment by Atremblay9** [comment]
Found some documentation in Vue-Cal for Timeless events: https://antoniandre.github.io/vue-cal/#ex--timeless-events and for min max dates: https://antoniandre.github.io/vue-cal/#ex--min-max-dates

**Comment by Atremblay9** [comment]
Another solution for multiDay events is the All Day prop: https://antoniandre.github.io/vue-cal/#ex--all-day-events

**Comment by johnjovero98** [comment]
**Another bug on multiday event**

I suddenly encountered this bug on the events page while working on the calendar.
The multiday event  (Develop Ed Hackathon) does not start and end at the right day on the website.

![image](https://github.com/user-attachments/assets/53a6aacb-b402-479d-88db-92a51fcc5bc1)

My best guess would be that without the "timeZone: ..." declared under the "start: {...}"  and "end: {...}" _dictionary_ 👀, it will default to GMT 0. 

It's kinda like declaring the "start.date" and "end.date" as:

"2024-11-08T00:00-00:00"
"2024-11-11T00:00-00:00"

Though the client side renders datetime in GMT -07 (mountain time) (probably because of our system settings?). Hence, the weird 5pm–5pm and the shift backwards on the days.

**console view:**
![image](https://github.com/user-attachments/assets/0975b4b6-c2e5-4581-aaf8-954a24a99094)
![image](https://github.com/user-attachments/assets/343db4aa-0cc4-47cb-894c-e4d40f9ec353)

I think this is an awesome problem to solve at open source club @dgmouris  👀

(P.S. datetimes does make a developer go craaazzehhhh!
Not to mention we are dealing with this as daylight saving is approaching🤯😵‍💫)

**Comment by MandyMeindersma** [comment]
When I was an intern I broke quickbooks for all of australia because of time zones and my coworkers showed me this video:

https://www.youtube.com/watch?v=-5wpm-gesOY

Wait until 6:35 ish, it's so worth it I promise hahaha

**Comment by charrde** [comment]
I've actually been working with timezones recently, and seeing this pop up again in my email. I do have a potential fix that appears to be working.

this is the patch I used for making them appear on the calendar recently, it's just an or statement.
```javascript
event.start.dateTime || event.start.date,
event.end.dateTime || event.end.date,
```

Replacing it with the below makes it end on the correct date... and makes the weekly calendar look less funky.

```javascript
(event.start.dateTime || `${event.start.date}T00:00:00`),
(event.end.dateTime || `${event.end.date}T23:59:59`),
```

I believe this will work okay because from what I can see date is being used for events that are considered all day.

> **Another bug on multiday event**
> 
> I suddenly encountered this bug on the events page while working on the calendar. The multiday event (Develop Ed Hackathon) does not start and end at the right day on the website.
> 
> ![379403509-53a6aacb-b402-479d-88db-92a51fcc5bc1](https://private-user-images.githubusercontent.com/144284522/379414941-92fd59d3-f969-4a7d-b882-e669c1e94417.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3MDg2NDMsIm5iZiI6MTcyOTcwODM0MywicGF0aCI6Ii8xNDQyODQ1MjIvMzc5NDE0OTQxLTkyZmQ1OWQzLWY5NjktNGE3ZC1iODgyLWU2NjljMWU5NDQxNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyM1QxODMyMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNjg1MzBkNmY5MzI5OTIyZGI2MDcwNzdiOWQyZDVhZTUwMGFkOWVmNjdiMzE0ZWRiNzg3MzY1MmYzOTc1NzI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.F5ms6F51A_oSfIroCcqodDeNS1QonNNu8wyJdarYljA)
> 
> My best guess would be that without the "timeZone: ..." declared under the "start: {...}" and "end: {...}" _dictionary_ 👀, it will default to GMT 0.
> 
> It's kinda like declaring the "start.date" and "end.date" as:
> 
> "2024-11-08T00:00-00:00" "2024-11-11T00:00-00:00"
> 
> Though the client side renders datetime in GMT -07 (mountain time) (probably because of our system settings?). Hence, the weird 5pm–5pm and the shift backwards on the days.
> 
> **console view:** ![image](https://private-user-images.githubusercontent.com/144284522/379407584-0975b4b6-c2e5-4581-aaf8-954a24a99094.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3MDg2NDMsIm5iZiI6MTcyOTcwODM0MywicGF0aCI6Ii8xNDQyODQ1MjIvMzc5NDA3NTg0LTA5NzViNGI2LWMyZTUtNDU4MS1hYWY4LTk1NGEyNGE5OTA5NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyM1QxODMyMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iOWQ3M2ZmZjE2NGQxZDM1NWQxNWFjMDRiNjFiNWRlODQ1NWM3YjVjZjAyZTU0MGEwYjQ4ZmE2MjhmYmU5NmNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.g4O5EnMEnTljTdYAn-2cEP5YkGc9gINt16a5xeqUU0c) ![image](https://private-user-images.githubusercontent.com/144284522/379407602-343db4aa-0cc4-47cb-894c-e4d40f9ec353.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3MDg2NDMsIm5iZiI6MTcyOTcwODM0MywicGF0aCI6Ii8xNDQyODQ1MjIvMzc5NDA3NjAyLTM0M2RiNGFhLTBjYzQtNDdjYi04OTRjLWU0ZDQwZjllYzM1My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyM1QxODMyMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNTM4ZjQzOTM5MjA3NWYyMjA5NDE2NzFiYjYyMmE0OWQ5YWFmZDlmOWE5MDMwZTdiNGRmYzA5NDZkYTJjZDczJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.RA9lxIJYqF7NH7iy9myoma7pBtKFDgLbEoFSrBt4GXU)
> 
> I think this is an awesome problem to solve at open source club @dgmouris 👀
> 
> (P.S. datetimes does make a developer go craaazzehhhh! Not to mention we are dealing with this as daylight saving is approaching🤯😵‍💫)

**Comment by johnjovero98** [comment]
> When I was an intern I broke quickbooks for all of australia because of time zones and my coworkers showed me this video:

OMG!!!!! I hope the australian businesses did not miss their tax and ASIC filing dates 😂

> https://www.youtube.com/watch?v=-5wpm-gesOY

Imagine if we were a type 3 civilization, and you got a call from another planet hahaha.

One of my instructors mentioned that datetimes are also her pet peeve.
They are very tricky to deal with!

**Comment by johnjovero98** [comment]
@charrde I tested it on my local repo and it works! I think that's an elegant fix! 👌

I over thought about solving this using unix epoch 🫡
